// Date: 10/21/2015 8:27:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package mythicalAccessories;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWings extends ModelBiped 
{
	//fields
	ModelRenderer winglefttop0;
	ModelRenderer wingleftwing0;
	ModelRenderer wingrighttop0;
	ModelRenderer wingrightwing0;
	ModelRenderer winglefttop1;
	ModelRenderer wingleftwing1;
	ModelRenderer wingrighttop1;
	ModelRenderer wingrightwing1;

	public ModelWings(float scale)
	{
		super(scale);
		textureWidth = 64;
		textureHeight = 32;
		
		winglefttop0 = new ModelRenderer(this, 32, 0);
		winglefttop0.addBox(1F, 0F, 2F, 6, 1, 1);
		winglefttop0.setRotationPoint(0F, 0F, 0F);
		winglefttop0.setTextureSize(64, 32);
		winglefttop0.mirror = true;
		setRotation(winglefttop0, 0F, -0.1832596F, 0F);
		wingleftwing0 = new ModelRenderer(this, 32, 2);
		wingleftwing0.addBox(1F, 1F, 2.5F, 6, 9, 0);
		wingleftwing0.setRotationPoint(0F, 0F, 0F);
		wingleftwing0.setTextureSize(64, 32);
		wingleftwing0.mirror = true;
		setRotation(wingleftwing0, 0F, -0.1832596F, 0F);
		wingrighttop0 = new ModelRenderer(this, 32, 0);
		wingrighttop0.addBox(-7F, 0F, 2F, 6, 1, 1);
		wingrighttop0.setRotationPoint(0F, 0F, 0F);
		wingrighttop0.setTextureSize(64, 32);
		wingrighttop0.mirror = true;
		setRotation(wingrighttop0, 0F, 0.1832596F, 0F);
		wingrightwing0 = new ModelRenderer(this, 32, 2);
		wingrightwing0.addBox(-7F, 1F, 2.5F, 6, 9, 0);
		wingrightwing0.setRotationPoint(0F, 0F, 0F);
		wingrightwing0.setTextureSize(64, 32);
		wingrightwing0.mirror = true;
		setRotation(wingrightwing0, 0F, 0.1832596F, 0F);
		winglefttop1 = new ModelRenderer(this, 32, 0);
		winglefttop1.addBox(6F, 1F, 1.5F, 6, 1, 1);
		winglefttop1.setRotationPoint(0F, 0F, 0F);
		winglefttop1.setTextureSize(64, 32);
		winglefttop1.mirror = true;
		setRotation(winglefttop1, 0.0349066F, -0.2617994F, -0.1832596F);
		wingleftwing1 = new ModelRenderer(this, 32, 2);
		wingleftwing1.addBox(6F, 2F, 2F, 6, 9, 0);
		wingleftwing1.setRotationPoint(0F, 0F, 0F);
		wingleftwing1.setTextureSize(64, 32);
		wingleftwing1.mirror = true;
		setRotation(wingleftwing1, 0.0349066F, -0.2617994F, -0.1832596F);
		wingrighttop1 = new ModelRenderer(this, 32, 0);
		wingrighttop1.addBox(-12F, 1F, 1.5F, 6, 1, 1);
		wingrighttop1.setRotationPoint(0F, 0F, 0F);
		wingrighttop1.setTextureSize(64, 32);
		wingrighttop1.mirror = true;
		setRotation(wingrighttop1, 0.0349066F, 0.2617994F, 0.1832596F);
		wingrightwing1 = new ModelRenderer(this, 32, 2);
		wingrightwing1.addBox(-12F, 2F, 2F, 6, 9, 0);
		wingrightwing1.setRotationPoint(0F, 0F, 0F);
		wingrightwing1.setTextureSize(64, 32);
		wingrightwing1.mirror = true;
		setRotation(wingrightwing1, 0.0349066F, 0.2617994F, 0.1832596F);
		
		this.bipedHead.addChild(winglefttop0);
		this.bipedHead.addChild(wingleftwing0);
		this.bipedHead.addChild(wingrighttop0);
		this.bipedHead.addChild(wingrightwing0);
		this.bipedHead.addChild(winglefttop1);
		this.bipedHead.addChild(wingleftwing1);
		this.bipedHead.addChild(wingrighttop1);
		this.bipedHead.addChild(wingrightwing1);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		winglefttop0.render(f5);
		wingleftwing0.render(f5);
		wingrighttop0.render(f5);
		wingrightwing0.render(f5);
		winglefttop1.render(f5);
		wingleftwing1.render(f5);
		wingrighttop1.render(f5);
		wingrightwing1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
